In [2]:
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

SyntaxError: invalid syntax (3013804036.py, line 1)

In [5]:
pip install uv


[notice] A new release of pip available: 22.2.2 -> 26.1.2
[notice] To update, run: C:\Users\varsh\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [1]:
import numpy as np
a = np.array([[1,2,3],
             [4,5,6]])
a.shape()

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy


     --------------------------------------- 12.9/12.9 MB 32.7 MB/s eta 0:00:00



[notice] A new release of pip available: 22.2.2 -> 26.1.2
[notice] To update, run: C:\Users\varsh\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
a = np.array([[1,2,3],
             [4,5,6]])
a.shape

(2, 3)

In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.zeros((3, 4))
c = np.arange(0, 20, 2)
d = np.linspace(0, 1, 5)

print(a.shape, a.dtype)
print(b.shape)
print(c)
print(d)

(5,) int64
(3, 4)
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


In [9]:
a = np.arange(12)

# try each one — predict first!
print(a.reshape(3, 4))
print(a.reshape(4, 3))
print(a.reshape(2, 2, 3))
print(a.reshape(2, -1))   

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [10]:
a = np.arange(25).reshape(5, 5)

print(a[0])        # first row
print(a[:, 0])     # first column
print(a[1:3, 2:4]) # submatrix
print(a[a > 10])   # boolean mask

[0 1 2 3 4]
[ 0  5 10 15 20]
[[ 7  8]
 [12 13]]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [12]:
import numpy as np
print (np.__version__)
np.show_config()

2.2.6
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.0",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7xf_vzet/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

C:\Users\varsh\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [15]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [17]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
a = np.arange(10,50)
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [21]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4]),)


In [25]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [28]:
a = np.random.random((3,3,3))
print(a)

[[[0.11172685 0.72176687 0.51376786]
  [0.75885534 0.5766235  0.61849009]
  [0.50723532 0.2747007  0.79413727]]

 [[0.40030856 0.26106773 0.85245459]
  [0.32901165 0.46581846 0.81331335]
  [0.95713515 0.62369132 0.93179622]]

 [[0.48924178 0.57635403 0.85150152]
  [0.77770898 0.47661873 0.95811979]
  [0.8311874  0.06807195 0.38160235]]]


In [30]:
a = np.random.random((10,10))
amax , amin = a.max(), a.min()
print(amax , amin)

0.9972716828289813 0.004413472278866237


In [31]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
a = np.ones((5,5))
a = np.pad(a, pad_width=1 , mode ='constant', constant_values = 0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [37]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [39]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [40]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [42]:
a = np.zeros((8,8), dtype=int)
a[1:2,::2] = 1
a[::2 ,1:2] = 1
print(a)

[[0 1 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [43]:

print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


In [45]:

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [46]:
a = np.random.random((5,5))
a = (a - np.mean(a)) / (np.std(a))
print(a)

[[-0.13257768 -0.20209464 -1.91014221 -1.21897419  1.38655734]
 [-1.4954661   0.33519898  1.44653566  0.73866455  0.40296548]
 [ 0.76181064 -1.56941067 -0.21554243 -1.06235797 -0.23954406]
 [-0.84177228 -0.79509842  0.28678051 -0.32697354 -0.81822386]
 [ 1.14898821  0.68181945  1.25343673  1.36406023  1.02136027]]


In [47]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [53]:
a = np.matmul(np.ones((5,3)) , np.ones(3,2)))
print(a)

SyntaxError: unmatched ')' (714505724.py, line 1)

In [54]:
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [56]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


In [57]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [58]:
uv add pandas

SyntaxError: invalid syntax (2039084212.py, line 1)

In [59]:
uv install pandas

SyntaxError: invalid syntax (766914739.py, line 1)

In [60]:
pip install pandas


[notice] A new release of pip available: 22.2.2 -> 26.1.2
[notice] To update, run: C:\Users\varsh\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip



     --------------------------------------- 11.3/11.3 MB 17.2 MB/s eta 0:00:00
     ------------------------------------- 349.3/349.3 kB 10.9 MB/s eta 0:00:00
     -------------------------------------- 510.1/510.1 kB 6.4 MB/s eta 0:00:00


In [74]:
import pandas as pd

calories = {"Day 1": 1750, "Day 2": 2100, "Day 3":1700}

series = pd.Series(calories)

print(series[series < 2000])

Day 1    1750
Day 3    1700
dtype: int64


In [90]:
# DataFrame = A tabular  data structure with rows and columns 2D 

import pandas as pd

data = {"Name":["Spongebob", "Patrick", "Squidward"],
        "Age":[30, 35, 50]
       }

df = pd.DataFrame(data, index=["Employee 1", "Employee 2", "Employee 3"])

#print(df)

# add new row
# new_row = pd.DataFrame([{"Name": "Sandy", "Age": 28, "job": "Engineer"}])

# df = pd.concat([df, new_row])

# print(df)




                 Name  Age       job
Employee 1  Spongebob   30       NaN
Employee 2    Patrick   35       NaN
Employee 3  Squidward   50       NaN
0               Sandy   28  Engineer


In [93]:
# importing csv , json

import pandas as pd

df = pd.read_csv(r"C:\Users\varsh\OneDrive\Desktop\data.csv")

print(df.to_string())


      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire       NaN     0.6     8.5          0
4      5  Charmeleon      Fire       NaN     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       NaN     0.5     9.0          0
7      8   Wartortle     Water       NaN     1.0    22.5          0
8      9   Blastoise     Water       NaN     1.6    85.5          0
9     10    Caterpie       Bug       NaN     0.3     2.9          0
10    11     Metapod       Bug       NaN     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6

In [7]:
# selection techniques using pandas
import pandas as pd

df = pd.read_csv(r"C:\Users\varsh\OneDrive\Desktop\data.csv")

# selection by column

# print(df["Name"].to_string())

#print(df[["Name", "Height", "Weight"]].to_string())

#slection by rows

# print(df.loc[0])

print(df[df["Name"]=="Pikachu"])





    No     Name     Type1 Type2  Height  Weight  Legendary
24  25  Pikachu  Electric   NaN     0.4     6.0          0


In [109]:
# filtering = keeping the rows that match a condition


df = pd.read_csv(r"C:\Users\varsh\OneDrive\Desktop\data.csv")

# tall_pokemon = df[df["Height"] >= 2]

# heavy_pokemon = df[df["Weight"] > 100]

legendary_pokemon = df[df["Legendary"] == 1]

print(legendary_pokemon.to_string())






      No      Name     Type1   Type2  Height  Weight  Legendary
143  144  Articuno       Ice  Flying     1.7    55.4          1
144  145    Zapdos  Electric  Flying     1.6    52.6          1
145  146   Moltres      Fire  Flying     2.0    60.0          1
149  150    Mewtwo   Psychic     NaN     2.0   122.0          1


In [120]:
# aggregation reduces a set of values into a single summary value , used to summarize and analyze the data ,
# often used with groupby() function

import pandas as pd 


df = pd.read_csv(r"C:\Users\varsh\OneDrive\Desktop\data.csv")

# print(df.mean(numeric_only = True))

# print(df.sum(numeric_only = True))


# single column

# print(df["Height"].mean())

# groupby()

# group = df.groupby("Type1")

# print(group["Height"].mean())





Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       1.083333
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64


In [130]:
# data cleaning = process of fixing / removing imcomplete , incorrect , or irrelevant data.pandas does 75 percent 
# of data cleaning

df = pd.read_csv(r"C:\Users\varsh\OneDrive\Desktop\data.csv")


 # drop irrelevant columns 
    
# df = df.drop(columns = [ "Legendary" , "No"])

# print(df)

# handling missing data

# df = df.dropna(subset=["Type2"])

df = df.fillna({"Type2": "None"})

print(df.to_string())



      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire      None     0.6     8.5          0
4      5  Charmeleon      Fire      None     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water      None     0.5     9.0          0
7      8   Wartortle     Water      None     1.0    22.5          0
8      9   Blastoise     Water      None     1.6    85.5          0
9     10    Caterpie       Bug      None     0.3     2.9          0
10    11     Metapod       Bug      None     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6

In [ ]:
# Matplotlib

In [1]:
pip install matplotlib


     ---------------------------------------- 8.2/8.2 MB 15.9 MB/s eta 0:00:00
     ---------------------------------------- 1.6/1.6 MB 20.0 MB/s eta 0:00:00
     ------------------------------------- 221.2/221.2 kB 14.1 MB/s eta 0:00:00
     ---------------------------------------- 73.4/73.4 kB 4.2 MB/s eta 0:00:00
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
     ---------------------------------------- 7.1/7.1 MB 19.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 26.1.2
[notice] To update, run: C:\Users\varsh\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [88]:
import matplotlib.pyplot as plt

import numpy as np

import pandas as pd

# x = np.array([ 2023, 2024, 2025, 2026])

# y = np.array([15, 25, 30, 20])

# plt.plot(x,y)

# plt.show()

# print(matplotlib.__version__)

# x = np.array([ 2023, 2024, 2025, 2026])

# y1 = np.array([15, 25, 30, 20])

# y2 = np.array([17, 23, 38, 5])

# y3 = np.array([13, 15, 20, 4])

# line_style = dict(marker = "." , markersize = 30, markerfacecolor = "blue", markeredgecolor= "green", linestyle= "solid",
#                   linewidth = 4, )  #color= "lightblue"
                  

# plt.plot(x , y1 , color ="red", **line_style)

# plt.plot(x , y2 , color = "pink", **line_style)

# plt.plot(x , y3 ,color = "yellow", **line_style)

# plt.show()


# labels 

# x = np.array([ 2023, 2024, 2025, 2026])

# y1 = np.array([15, 25, 30, 20])

# y2 = np.array([17, 23, 38, 5])

# y3 = np.array([13, 15, 20, 4])

# plt.title("Class size", fontsize = 20, family = "Arial", fontweight = "bold", color ="darkblue")

# plt.xlabel("Year", fontsize = 20, family ="Arial", fontweight = "bold", color = "lightblue")

# plt.ylabel("Students", fontsize = 20, family ="Arial", fontweight = "bold", color = "lightblue")

# plt.tick_params(axis = "both", colors ="darkblue")



# plt.plot(x , y1)

# plt.plot(x , y2)

# plt.plot(x , y3)

# plt.xticks(x)

# plt.show()

#grid lines = helps male plots easier to read by adding ref lines

# x = [1,2,3,4,5]

# y = [5,10,15,20,25]

# plt.grid(axis ="y", linewidth = 2, color = "lightgray", linestyle="dashed")

# plt.plot(x,y)

# plt.show()

#barcharts = compares categorie of data

# categories = np.array(["Grains", "Fruit", "Vegetables", "Protein", "Dairy", "Sweets"])

# values = [4,3,2,5,3,1]

# #plt.bar(categories , values, color = "skyblue")

# plt.barh(categories , values, color = "skyblue")


# plt.title("Daily Consumption")

# plt.xlabel("Food")

# plt.ylabel("Quantity")

# plt.show()



#piecharts


# categories = ["Freshmen", "Sophomore","Juniors", "Seniors"]

# values = np.array([300, 250, 275, 225])

# colors = ["red","yellow", "blue", "green"]

# plt.pie(values, labels= categories, autopct= "%1.1f%%", colors = colors, explode = [0,0,0,0.1], shadow = True,
#         startangle = 90)

# plt.title("Bro code")

# plt.show()



# scatter graphs = relationship between two variables , correlation



# x1 = np.array([0 , 1, 1, 2, 3, 4 , 5, 6, 7, 7, 8])

# y1 = np.array([55, 60, 65, 62, 68, 70 , 75 , 78, 82 , 85 ,87])

# x2 = np.array([0 , 1, 2,2,3,4,5,6,7,7,8])

# y2 = np.array([50, 58, 65, 70, 72,78, 83,88,92,95,97])


# plt.scatter(x1 , y1, color= "blue",
#             alpha = 0.5,
#             s= 50,
#             label = "Class A")

# plt.scatter(x2 , y2, color= "red",
#             alpha = 0.5,
#             s= 50,
#             label = "Class B")




# plt.xlabel("Hours studied")

# plt.ylabel("Grade")

# plt.title("Test scores")

# plt.legend()

# plt.show()




#histograms = distribution of quantitative data , intervals(bins)

# scores = np.random.normal(loc=80, scale=10, size=100)

# scores = np.clip(scores, 0, 100)

# plt.hist(scores, bins=10, color ="lightgreen", edgecolor = "black")

# plt.title("Exam scores")

# plt.xlabel("score")

# plt.ylabel("No.of students")

# plt.show()



# subplots 
# figure = the entire canvas 
# Ax = a single subplot

# x = np.array([1,2,3,4,5])

# figure , axes = plt.subplots(2,2)

# axes[0,0].plot(x, x*2, color ="red")

# axes[0,0].set_title("x*2")

# axes[0,1].plot(x , x**2, color = "blue")

# axes[0,1].set_title("x**2")

# axes[1,0].plot(x, x**3, color="green")

# axes[1,0].set_title("x**3")

# axes[1,1].plot(x,x**4, color="yellow")

# axes[1,1].set_title("x**4")

# plt.tight_layout()

# plt.show()


#using pandas and matplotlib


# df = pd.read_csv(r"C:\Users\varsh\OneDrive\Desktop\data.csv")

d#f = pd.read_csv(r"C:\Users\varsh\OneDrive\Desktop\data.csv")










